language: node_js
node_js:
  - "node"
  - "7"
  - "6"
  - "5"
  - "4"
  - "lts/*"
install:
  - npm install
  - npm install -g codecov
  - npm install -g istanbul
script:
  - standard src/
  - istanbul cover test/testflow.js
  - codecov
env:
  CODECLIMATE_REPO_TOKEN: a174b03227cdc953c831f45bebcf0af357ec1b8a4b8477f36444c16f084a409f
